title: Junho Kim
logo: /assets/img/profile_photo.jpg
description: “I am not a visionary. I'm an engineer. I'm happy with the people who are wandering around looking at the stars but I am looking at the ground and I want to fix the pothole before I fall in.”― Linus Torvalds
show_downloads: true
theme: jekyll-theme-minimal
